apiVersion: core.artifacthub.io/v1alpha1
kind: ArtifactHub
metadata:
  labels:
    app.kubernetes.io/name: artifacthub-operator
    app.kubernetes.io/managed-by: kustomize
  name: artifacthub-sample
spec:
  version: "v1.21.0"
  allowPrivateRepositories: true
  allowUserSignUp: true
